### ISSUE TITLE
같이 Tutorial 문서화 및 리뷰에 참여하고 싶으신 분을 모집합니다.

### ISSUE THREAD

**Issue by heumsi** [SoogoonSoogoonPythonists/sqlalchemy-for-pythonist#2]
## 배경

sqlalchemy는 DB와 연동된 작업을 할 때 많이 쓰이는 도구입니다.
저는 필요에 따라 구글링해서 써보기는 했으나, 뭔가 제대로 안다고 느낀적이 없었네요.
그러다 빈번히 작업이 막히거나, 구글링하는데 시간을 쏟곤 했습니다.

파이썬으로 개발을 하는 사람이라면 sqlalchemy에 대해 한 번쯤은 제대로 알고가야하지 않나 싶은 생각이 점점 들었는데요.
생각만 하다가 이번 기회를 통해 한 번 제대로 공부해야겠단 결심이 섰습니다.

현재의 sqlalchemy 문서는 굉장히 딱딱한데요. 초보자가 보기에 이것저것 잘 모르는 용어들과 내용이 마구 튀어나오곤 합니다.
이에, 공식 문서를 정독하며 한글화 + 좀 더 쉽게 읽을 수 있도록 만드는 작업을 해보고 싶습니다.
혼자 하는거보단, 같이 하는게 더 동기부여되고 성취감이 있을거 같아, 같이 해보실분을 모집해봅니다.

<br>

## 목표

일단 첫 번째 목표는 [sqlalchemy 공식 홈페이지에 있는 튜토리얼 문서](https://docs.sqlalchemy.org/en/14/tutorial/index.html#unified-tutorial)를 읽고 정리하는 것입니다.
정리는 한글로 하고, 초보자도 친숙히 읽기 쉽도록 적당히 정리하는 것이 목표입니다.

<br>

## 계획

튜토리얼은 다음과 같은 목차로 되어있습니다.

1. Tutorial Overview
2. Establishing Connectivity - the Engine
3. Working with Transactions and the DBAPI
4. Working with Database Metadata
5. Working with Data
6. Data Manipulation with the ORM
7. Working with Related Objects
8. Further Reading

튜토리얼인 만큼 목차 순서도 중요하다고 생각합니다. 
따라서 매 주마다 한 명이 목차요소 하나를 정리합니다.
예를 들면, 현재 1~3은 제가 이미 정리를 해놨으므로([여기서](https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/tree/main/tutorial) 확인하실 수 있습니다.), 다음 순서에 해당하는 분이 4번 내용을 정리해주시면 됩니다.
그 다음주 순서에 해당하는 분은 5번이 되겠구요. 이렇게 8번까지 정리하게 되고, 총 5주 동안 진행되겠네요.
이 순서의 간격을 '매주'가 아니라 다르게 할지, 담당 내용의 범위는 적정한지는 논의해보면 좋을듯 합니다.

매번 올라오는 글은 PR을 통해 공유되고, 멤버들이 리뷰해줍니다.
예를 들어, 내용을 읽다가 이 내용이 이해가 가지 않는다는지 (그렇다면 추가 설명 내용을 붙여주면 좋겠죠)
비문이 있다든가, 단어가 혼용되었다든가 등의 내용이 리뷰에 담기게 됩니다.

PR 제목, 커밋 메시지 규칙, Merge 방법은 제가 추후에 가이드하겠습니다.

<br>

## 덧붙이는 말

지금은 대충 범위와 목표만 잡은 상태입니다.
활동 방법 등 실행가능한 더 좋은 아이디어가 있으시면 말씀해주세요.

참여하고 싶으신 분은 아래 코멘트 달아주시면 되겠습니다!
궁금하신 것도 있으시면 적어주세요~!

**Comment by Hyeonproject** [comment]
부족한 영어솜씨와 개발솜씨를 가지고 있지만, 카카오톡의 홍보글을 통해서 조금씩 시간을 내어서 **참가하고 싶습니다**.
> 무지성 참가해서 유지성으로 나가고 싶습니다.

**Comment by comnamu18** [comment]
참여방식은 어떻게 되는 건가요? PR 날리면 검토 후 받아주시는 건가요??

**Comment by definity-smileY** [comment]
파이썬기반으로 개발하고 있습니다. ORM에 있어서 깊이 있게 파고드는 욕심이 있어 이렇게 참가합니다!

**Comment by icehongssii** [comment]
지금은 실행가능한 좋은 아이디어는 생각은 안나지만 일단은 참가 희망합니다 👍

**Comment by hyelin2** [comment]
부족하지만 참가하고 싶습니다!

**Comment by heumsi** [comment]
> 참여방식은 어떻게 되는 건가요? PR 날리면 검토 후 받아주시는 건가요??

네 그렇습니다. 멤버 모두 리뷰합니다

**Comment by heumsi** [comment]
이번주 목요일까지 더 기다려보겠습니다!

이후 레포 멤버 인비드리고 다시 노티드리겠습니다!

**Comment by heumsi** [comment]
@Hyeonproject @comnamu18 @definity-smileY @icehongssii @icehongssii 

위에 다섯 분 모두 레포의 Write 권한을 가진 멤버로 인비 드렸습니다.
아래 내용 읽어보시고, 계속해서 참여 희망하시면 수락해주시면 됩니다!

---

남은 목차 내용이 아래 5개 인데요.
한 주에 한 분이 하나씩 정리해서 PR & Merge 하면 어떨까 싶습니다.

```
4. Working with Database Metadata
5. Working with Data
6. Data Manipulation with the ORM
7. Working with Related Objects
8. Further Reading
```

이렇게 생각하고 있습니다.

- 매주 일요일까지 이번주에 누가 정리할 지 정합니다.
  - 제가 Issue 를 만들어두겠습니다.
  - 그 주에 하고 싶으신 분은 이슈에 멘션 달아주시면 제가 issue assign 하겠습니다.
- assign 받으신 분은 월~수까지 문서를 읽고 한글로 정리합니다.
  - feature 브랜치 새로 파서 작업하시고, main 으로 PR 날려주시면 됩니다.
  - 이후 목~토까지 멤버들의 리뷰 후 머지합니다.
  - 목요일 저녁까지 1차 리뷰를 합니다.
  - 금요일 저녁까지 2차 리뷰를 합니다.
  - 토요일 저녁까지 3차 리뷰를 합니다. 3차 리뷰가 마지막이고 이후 Squash & Merge 합니다.
  - 리뷰의 기준은 "읽기 쉬운지? 이해하기 어려운 부분은 없는지? (있다면 추가 설명을 달아주면 좋겠습니다 이런 리뷰)"입니다.
  - 리뷰는 모든 멤버가 참여합니다. 
- 상황에 따라서 assgin 할 사람이 등장하지 않으면 제가 하겠습니다.

소통은 GitHub Issue로 하고, 작업 내용은 PR 을 통해 봅니다.

궁금하신 점 있으시면 말씀해주세요!
저는 4장을 담당할 이슈를 만들어두겠습니다 ㅎㅎ

**Comment by heumsi** [comment]
멤버 모집 마감으로 이슈를 Close 합니다.
