### ISSUE TITLE
Tutorial - 4. Working with Database Metadata 정리

### ISSUE THREAD

**Issue by heumsi** [SoogoonSoogoonPythonists/sqlalchemy-for-pythonist#3]
## TLDR

Tutorial - 4. Working with Database Metadata 을 읽고 정리합니다.

## 기간

- 2021-07-12(월) ~ 2021-07-14(수): 작업
- 2021-07-15(목) ~ 2021-07-17(토): 리뷰 & 반영
- 2021-07-18(일) : Merge

## 담당자

이 파트 맡고 싶으신 분은 멘션 달아주세요~

**Comment by Hyeonproject** [comment]
저가 먼저 맡아서 해보겠습니다.
수요일 전까지 작업을 완료하고 피드백 받아보고 싶습니다!

**Comment by Hyeonproject** [comment]
commit 글 형식을 읽어보지 않고 막 적었네요. 
조심하겠습니다.

**Comment by heumsi** [comment]
새로 브랜치 파서 커밋하시면 됩니다. 
Squash & Merge 할 때만 커밋 규칙에 맞춰서 들어가면 되기 때문에 직접 파신 브랜치 상에서의 커밋은 크게 형식 신경 안쓰셔도 됩니다.

**Comment by heumsi** [comment]
@Hyeonproject 오늘까지 작업 완료 부탁드립니다!

작업 이후 PR 올려주시고, 리뷰어 모든 멤버로 지정해주세요ㅎㅎ

**Comment by Hyeonproject** [comment]
리뷰어 올리는 것을 깜빡했습니다. 잘 부탁드리고, 업무가 끝나고 나면 다시 한번 더 검토할 계획입니다. 감사합니다.
