### ISSUE TITLE
Tutorial - 5. Working with Data

### ISSUE THREAD

**Issue by heumsi** [SoogoonSoogoonPythonists/sqlalchemy-for-pythonist#6]
https://docs.sqlalchemy.org/en/14/tutorial/data.html

- [x] #13
- [x] #14
- [x] #15

**Comment by icehongssii** [comment]
@heumsi  해당 챕터 번역 희망합니다 👍

**Comment by socar-hardy** [comment]
이거 내용이 좀 많아서, 혼자 다 하시기는 힘들거 같은데.. 
분량을 좀 나눠볼까 생각이 듭니다.

**Comment by heumsi** [comment]
이거 내용이 좀 많아서, 혼자 다 하시기는 힘들거 같은데.. 
분량을 좀 나눠볼까 고민이 됩니다 ..

**Comment by icehongssii** [comment]
아 이런  select 관련 챕터가 압권이었네요.

- insert+update
- select로 나누면 어떨까요?

만약 두개로 나눈다면 select 관련 챕터 담당해보겠습니다

**Comment by heumsi** [comment]
좋습니다!

서브 테스크로 나누겠습니다!

- [ ] Inserting Rows with Core 
- [ ] Selecting Rows with Core or ORM
- [ ] Updating and Deleting Rows with Core

**Comment by heumsi** [comment]
#13, #15 같이 맡아주실 분 있을까요?
마찬가지로 차주(월~수)에 해주시면 됩니다.

**Comment by hyelin2** [comment]
13,15 번역 희망합니다 :)

**Comment by socar-hardy** [comment]
> 13,15 번역 희망합니다 :)

넵 ㅎㅎ
이 링크 확인한번 부탁드립니다.

https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/discussions/12
